#-------------------------------
# Site Settings
title: ZYQC
logo: # You can add own logo. For example '/images/logo.png'.
description: Norlin – A Beautiful Dark Blog Theme for Jekyll.


#-------------------------------
# Navigation Settings
menu-settings:
  menu-items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Publication'
      url: '/publication/'
    - title: 'News'
      url: '/news/'


#-------------------------------
# Author Settings
author:
  name: Yuqicheng Zhu
  avatar: '/images/me.jpg'


#-------------------------------
# Hero Settings
hero:
  title: Yuqicheng Zhu
  description: Art -> Engineering -> AI Research
  image: '/images/01.jpg'


#-------------------------------
# Contact Settings
contact:
  email: zhuyuqicheng@gmail.com # Add your email for contact form
  description: Feel free to reach out if you're interested in collaborating. (Sending an email to zhuyuqicheng@gmail is simpler). # Add a description of your form

# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
social:
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/yuqicheng-zhu-531658161/"}
- {icon: "ion-logo-github", link: "https://github.com/ZhuYuqicheng"}
- {icon: "ion-logo-twitter", link: "https://twitter.com/YuqichengZ"}
- {icon: "ion-logo-google", link: "https://scholar.google.com/citations?user=TE5jy5cAAAAJ&hl=en"}
- {icon: "ion-logo-pinterest", link: "https://pin.it/2gnZ7rx"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social/"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: zyqc # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
mailchimp-button-text: Join